# Generated by Django 4.1.1 on 2022-09-19 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import common.base.daobase


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AliyunDrive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=128, verbose_name="用户名")),
                ("nick_name", models.CharField(max_length=128, verbose_name="昵称")),
                ("user_id", models.CharField(max_length=32, verbose_name="用户ID")),
                (
                    "default_drive_id",
                    models.CharField(max_length=16, verbose_name="存储ID"),
                ),
                (
                    "default_sbox_drive_id",
                    models.CharField(max_length=16, verbose_name="保险箱ID"),
                ),
                (
                    "access_token",
                    common.base.daobase.AESCharField(
                        max_length=1536, verbose_name="访问token"
                    ),
                ),
                (
                    "refresh_token",
                    common.base.daobase.AESCharField(
                        max_length=512, verbose_name="刷新token"
                    ),
                ),
                ("avatar", models.CharField(max_length=512, verbose_name="头像地址")),
                ("used_size", models.BigIntegerField(default=0, verbose_name="已经使用空间")),
                ("total_size", models.BigIntegerField(default=0, verbose_name="总空间大小")),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=256, verbose_name="备注信息"
                    ),
                ),
                ("enable", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "private",
                    models.BooleanField(
                        default=True, verbose_name="是否私有，若设置为否，则该网盘可被其他用户进行上传下载"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="密钥是否可用")),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "owner_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "阿里云网盘认证信息",
                "verbose_name_plural": "阿里云网盘认证信息",
                "unique_together": {("owner_id", "user_id")},
            },
        ),
        migrations.CreateModel(
            name="FileInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="文件名字")),
                ("file_id", models.CharField(max_length=64, verbose_name="文件id")),
                ("drive_id", models.CharField(max_length=64, verbose_name="drive_id")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                ("size", models.BigIntegerField(verbose_name="文件大小")),
                ("content_type", models.CharField(max_length=64, verbose_name="文件类型")),
                (
                    "content_hash",
                    models.CharField(max_length=64, verbose_name="content_hash"),
                ),
                (
                    "crc64_hash",
                    models.CharField(max_length=64, verbose_name="crc64_hash"),
                ),
                ("downloads", models.BigIntegerField(default=0, verbose_name="下载次数")),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, verbose_name="备注信息"),
                ),
                (
                    "aliyun_drive_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.aliyundrive",
                        verbose_name="所属阿里云盘ID",
                    ),
                ),
                (
                    "owner_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户ID",
                    ),
                ),
            ],
            options={"verbose_name": "文件信息", "verbose_name_plural": "文件信息", },
        ),
        migrations.CreateModel(
            name="ShareCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "short",
                    models.CharField(
                        db_index=True, max_length=16, unique=True, verbose_name="短链接"
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("expired_time", models.DateTimeField(null=True, verbose_name="失效时间")),
                (
                    "password",
                    models.CharField(max_length=16, null=True, verbose_name="访问密码"),
                ),
                (
                    "file_id",
                    models.ManyToManyField(to="api.fileinfo", verbose_name="文件ID"),
                ),
                (
                    "owner_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户ID",
                    ),
                ),
            ],
            options={"verbose_name": "分享信息", "verbose_name_plural": "分享信息", },
        ),
    ]
