# Generated by Django 4.0.8 on 2023-02-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliyundrive',
            name='x_device_id',
            field=models.CharField(default='', max_length=128, verbose_name='设备ID'),
            preserve_default=False,
        ),
    ]
